<%
  config_path = if Fizzy.saas?
    gem_path = Gem::Specification.find_by_name("fizzy-saas").gem_dir
    File.join(gem_path, "config", "storage.yml")
  else
    File.join(__dir__, "storage.oss.yml")
  end
%>
<%= ERB.new(File.read(config_path)).result %>

google:
  service: GCS
  project: <%= ENV.fetch("GCS_PROJECT", "") %>
  credentials: <%= ENV.fetch("GCS_CREDENTIALS", "{}") %>
  bucket: <%= ENV.fetch("GCS_BUCKET", "") %>